Repository 2023WB-TeamB/Backend, pull requests merged in 2024-01, with the labels that each got.

#8 [feat] 회원가입/로그인/로그아웃 구현
  .gitignore
  docs/migrations/__init__.py
  gtd/settings.py
  gtd/urls.py
  requirements.txt
  users/migrations/__init__.py
  users/models.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: 기능구현

#10 [fix]response 값 수정
  users/views.py
Labels: 오류 수정

#15 [Feat] 문서 생성 Mock API 구현
  .gitignore
  docs/models.py
  docs/serializer.py
  docs/urls.py
  docs/views.py
  gtd/settings.py
  gtd/urls.py
Labels: 기능구현

#20 fix : AbstractBaseUser Class 수정
  users/models.py
Labels: 오류 수정

#24 [fix/#23] docker-compose 및 requirements 수정
  Dockerfile
  docker-compose.dev.yml
  requirements.txt
Labels: 오류 수정

#25 [feat/#21] 문서 공유 기능 구현
  docs/serializer.py
  docs/urls.py
  docs/views.py
  requirements.txt
Labels: 기능구현

#27 [chore/#26]: github actions deploy 파일 추가
  .github/workflows /django_deploy.yml
Labels: 환경설정

#30 [fix/#29] 문서 공유 에러 핸들링 추가
  docs/views.py
Labels: 오류 수정

#33 [fix/#32] 문서 공유 에러 핸들링 추가
  docs/views.py
Labels: 오류 수정

#35 [fix/#34] 문서 생성 API 에러 핸들링 및 Request Body 형식 수정
  docs/views.py
Labels: 오류 수정

#40 [feat] swagger 적용
  gtd/urls.py
  users/views.py
Labels: 기능구현

#42 [feat/#41] 문서 공유 기능 추가
  docs/views.py
Labels: 기능구현

#44 [feat] swagger custom, login response 값 수정
  gtd/settings.py
  users/serializers.py
  users/views.py
Labels: 기능구현

#50 [fix/#49]: 문서 조회 엔드포인트 변경
  docs/urls.py
  docs/views.py
Labels: 오류 수정

#52 [Feat/#51] 컨트리뷰터 생성 API 구현
  docs/urls.py
  docs/views.py
  requirements.txt
Labels: 기능구현

#58 [feat] Validation, Swagger Custom, Color 필드 추가
  docs/models.py
  docs/serializers.py
  docs/urls.py
  docs/views.py
  users/utils.py
Labels: 오류 수정, 기능구현

#59 [feat/#57] RabbitMQ 및 Celery 추가
  docker-compose.dev.yml
  docs/AiTask.py
  docs/github.py
  docs/views.py
  gtd/celery.py
  gtd/settings.py
  requirements.txt
Labels: 오류 수정, 기능구현

#53 [feat/#36] 문서생성 AI 연결 구현
  docs/github.py
  docs/views.py
  requirements.txt
Labels: 기능구현

#69 [feat/#65/taehee] 뱃지 기능 구현
  badge/__init__.py
  badge/admin.py
  badge/apps.py
  badge/models.py
  badge/tests.py
  badge/urls.py
  badge/views.py
  gtd/settings.py
  gtd/urls.py
  templates/tag/profile.html
Labels: 기능구현, 환경설정

#71 [chore/#60] Gunicorn 및 모니터링 툴 추가
  docker-compose.dev.yml
  gtd/settings.py
  gtd/urls.py
  prometheus.yml
  requirements.txt
Labels: 기능구현, 환경설정

#76 feat : 문서조회 response 수정일 기준으로 정렬
  docs/views.py
Labels: 기능구현

#78 [fix/#77] Badge API Endpoint 수정
  gtd/urls.py
Labels: 오류 수정

#80 [feat/#79] 문서 검색 API 구현
  docs/models.py
  docs/serializers.py
  docs/urls.py
  docs/views.py
Labels: 기능구현

#82 [refactor/#81] 문서 공유 Serializer 삭제
  docs/serializers.py
Labels: 리팩토링

#89 Fix/#83
  docs/serializers.py
  docs/views.py
Labels: 오류 수정

#94 Fix/#92
  docs/github.py
  docs/serializers.py
  docs/views.py
Labels: 오류 수정

#91 [Fix/#90] 문서 검색 response data 수정
  docs/serializers.py
Labels: 오류 수정

#85 [feat/#84] 문서 검색 API swagger 적용
  docs/serializers.py
  docs/views.py
Labels: 기능구현

#100 [fix/#99] 문서 검색 response data 수
  docs/serializers.py
Labels: 오류 수정

#97 [feat/#93] 뱃지 추가 디자인
  badge/tech_stack_images.py
  badge/theme.py
  badge/views.py
  templates/tag/card1.html
  templates/tag/terminal1.html
  templates/tag/terminal2.html
Labels: 기능구현, 리팩토링

#96 [Fix] swagger schema 수정
  badge/views.py
  docs/serializers.py
  docs/views.py
  users/urls.py
  users/views.py
Labels: 오류 수정

#103 [Fix/#102] 문서 검색 API 메소드 변경
  docs/views.py
Labels: 오류 수정

#110 [Fix] 스웨거 수정 및 리프레쉬 url 주석처리
  docs/views.py
  gtd/urls.py
  users/urls.py
  users/views.py
Labels: 오류 수정, 리팩토링

#108 [feat/#107] 문서 재생성 로직 개선 추가
  docs/AiTask.py
  docs/github.py
  docs/models.py
  docs/views.py
Labels: 기능구현, 리팩토링

#117 [Fix/#114] 프레임워크 추가 구현
  docs/github.py
Labels: 오류 수정

#120 [fix] 문서 버전별 조회 키워드 반환값 수정
  docs/views.py
Labels: 오류 수정

#116 [fix/#115] Message 전송 최적화 및 length 제한 로직 구현
  docs/github.py
  docs/views.py
Labels: 오류 수정

#122 [feat/#121] Repository code 수집 로직 개선
  docs/AiTask.py
  docs/github.py
  docs/views.py
Labels: 기능구현

#130 [fix/#125]: bfs -> dfs & 문자열 초과현상 수정
  docs/github.py
Labels: 오류 수정

#128 [Refactor] terminal 1뱃지 사이즈 조정
  templates/tag/terminal1.html
Labels: 오류 수정, 리팩토링

#132 [feat/#131] Title 생성 모델 분리 및 재생성에도 적용
  docs/github.py
  docs/views.py
Labels: 기능구현, 리팩토링

#137 [feat/#135] 공유 문서 조회 API 구현
  docs/views.py
Labels: 기능구현

#138 [feat/#133] 모델 분리
  docs/AiTask.py
  docs/github.py
  docs/views.py
Labels: 기능구현, 리팩토링

#141 [fix/#140] 공유 문서 조회 API response data 수정
  docs/serializers.py
  docs/views.py
Labels: 오류 수정

#144 s3 + cloudfront + lambda@Edge
  docs/urls.py
  docs/views.py
  gtd/settings.py
  requirements.txt
Labels: 기능구현

#151 [fix/#150] 문서 공유 url 형식 수정
  docs/views.py
Labels: 오류 수정
